version: "3.7"
services:
  web:
    container_name: nest
    build: .
    ports:
      - "3080:3080"
    networks:
      - webnet
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    # volumes:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # - postgres_data:/var/lib/postgresql/data/
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dev

networks:
  webnet:
# volumes:
#   postgres_data: